kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
data:
  masto.domain: {{ .Values.global.masto.domain | quote }}
  geocoder.useragent: {{ .Values.geocoder.useragent | quote }}
  cache.svc: {{ .Values.cache.svc | quote }}
  queue.svc: {{ .Values.global.queue.svc | quote }}
  queue.queue: {{ .Values.global.queue.queue | quote }}
  masto.visibility: {{ .Values.masto.visibility | quote }}
  nrel.stationnamelength: {{ .Values.nrel.stationnamelength | quote }}
  masto.postsize: {{ .Values.masto.postsize | quote }}

---

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secure-config
type: Opaque
data:
  masto.posttoken: {{ .Values.masto.posttoken | b64enc | quote }}
  nrel.token: {{ .Values.nrel.token | b64enc | quote }}
  queue.consumeruser: {{ .Values.queue.consumeruser | b64enc | quote }}
  queue.consumerpassword: {{ .Values.queue.consumerpassword | b64enc | quote }}

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deploy
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-c
        image: santisbon/evworker:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: {{ .Chart.Name }}-secret-vol
          mountPath: /etc/{{ .Chart.Name }}-secret-vol
          readOnly: true
        - name: {{ .Chart.Name }}-config-vol
          mountPath: /etc/{{ .Chart.Name }}-config-vol
          readOnly: true
        env:
        - name: TZ
          value: "America/Chicago"
        - name: ENVIRONMENT
          value: k8s
      initContainers:
      - name: init-{{ .Chart.Name }}-c
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup {{ .Release.Name }}-rabbitmq.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for queue service; sleep 2; done"]    
      volumes:
      - name: {{ .Chart.Name }}-secret-vol
        secret: 
          secretName: {{ .Release.Name }}-{{ .Chart.Name }}-secure-config
      - name: {{ .Chart.Name }}-config-vol
        configMap:
          name: {{ .Release.Name }}-{{ .Chart.Name }}-config
      restartPolicy: Always

---

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-{{ .Chart.Name }}-deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50